# Generated by Django 3.2.8 on 2021-10-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataset_entry',
            new_name='DatasetEntry',
        ),
        migrations.RenameModel(
            old_name='dataset_model',
            new_name='DatasetModel',
        ),
    ]
