# Generated by Django 3.2.6 on 2021-08-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_name', models.CharField(max_length=200)),
                ('algo_type', models.CharField(max_length=200)),
                ('dataset', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['algo_name'],
            },
        ),
    ]
