# Generated by Django 3.2.6 on 2021-08-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_data', '0004_dataset_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset_entry',
            options={'ordering': ['article_dataset']},
        ),
        migrations.AddField(
            model_name='dataset_entry',
            name='articles_Non_Alphanumeric',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataset_entry',
            name='article_dataset',
            field=models.CharField(max_length=200),
        ),
    ]
