# Generated by Django 3.2.6 on 2021-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('articles_nb_pages', models.IntegerField(default=0)),
                ('articles_nb_text', models.IntegerField(default=0)),
                ('article_text', models.TextField()),
                ('articles_lemmes', models.TextField()),
                ('article_class', models.CharField(max_length=200)),
                ('articles_Non_Alphanumeric', models.IntegerField(default=0)),
                ('article_dataset', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['article_dataset'],
            },
        ),
        migrations.CreateModel(
            name='dataset_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
